site_name: ASKO Wiki
site_url: https://docs.asko24.at/
theme:
  name: material
  language: de
docs_dir: docs
site_dir: ../site
use_directory_urls: true
plugins: []
extra:
  version: 16.05.2026-6
  version_date: '2026-05-20'
